### ISSUE TITLE
Add the 6T

### ISSUE THREAD

**Issue by qeqar** [angela-d/firmware_oneplus#5]
Hello,

is it possible to add the 6T? Or is the Zip/Firmware to different.
I would invest some time, but i never worked with such stuff before.

**Comment by angela-d** [comment]
I experimented with the 6 series a while back and the file structure wasn't exact and I didn't have a 6/6T to work with, that's why I did a filter to explicitly reject it.

Is your 6T a daily driver, or something you'd be able to experiment with?

**Comment by qeqar** [comment]
It is may daily drive, But i need to update the firmware before the next upgrade.
So i would have some testing time. Otherwise i will not get any updates, but that is why i use LinageOS :-)

So with what can i start?

**Comment by angela-d** [comment]
It is very risky messing with a daily driver, but if it's important to you, here's a breakdown of how this works.  If you are able to get this going without bricking your device, please submit a pull request!

- [Grab a 3/5/5T download](https://www.oneplus.com/support/softwareupgrade) to browse with so you get a feel of the directory hierarchy of the script, first.

[Updater script](https://github.com/angela-d/firmware_oneplus/tree/master/update)
- This is originally extracted from official Oneplus zips (`META-INF/com/google/android/updater-script`) - though modified, so you aren't simply flashing Oxygen and only taking on the bits you need.


1. The files we need (modem/firmware components) are all laid out in the Updater script referenced above.  Note their paths in the updater script and the extract script.
2. Now, take a look at the [extract script](https://github.com/angela-d/firmware_oneplus/blob/master/extract) 
3. First problem, the version check: `if [ "$(grep "\"OnePlus $VERSION\"" -R tmp/META-INF/com/google/android/ | wc -l)" == '0' ];` -- `META-INF/com/google/android/` does not exist in the Oneplus 6T OxygenOS zip.  We could do a condition, though (if 6T was entered), to peek at `META-INF/com/android/metadata` to grab the **pre-device** variable.  So that's not necessarily a problem.
4. Next up: 
```bash 
unzip -q "$OXYGEN_PATH" firmware-update/* -d "tmp/"
unzip -jq "$OXYGEN_PATH" RADIO/* -d "tmp/firmware-update/"
```
- `RADIO/` doesn't exist in 6T
- `firmware-update/` doesn't exist in 6T

So I'm not actually sure where the update is, it might be in a giant binary blob (presumably payload.bin?) which complicates extracting *only* the firmware & modems.

Another thing that throws me off ([from official Lineage instructions](https://wiki.lineageos.org/devices/fajita/install)):
> In some cases slot b can be unpopulated or contain much older firmware than slot a, leading to various issues including a potential hard-brick. We can ensure none of that will happen by copying the contents of slot a to slot b. 

6T is an A/B device, so that adds another layer of complexity.

***

I saw this posted on XDA, I'm not sure if it's using the same logic to extract or not, but it's worth a shot, too: https://f-droid.org/en/packages/fr.witchdoctors.c4ffein.oosfirmwareextractor/

**Comment by qeqar** [comment]
Ok, thanks, will have a look, bit bricking the device would not be that good.

**Comment by timehlers** [comment]
I have the same problem with my new Oneplus Nord. The firmware is like for the 6T a big payload.bin file. But this is no problem, you can slice it into the partition files with https://github.com/vm03/payload_dumper.git

But now you have a lot more partition files than I had on the OnePlus 5. I divided the files by name into 3 groups:

1. files which come from LineageOS, so presumable not to flash:

boot.img
dtbo.img
odm.img
product.img
recovery.img
system.img
vbmeta.img
vbmeta_system.img
vendor.img

2. Files known from OnePlus 5:

abl.img
devcfg.img
hyp.img
keymaster.img
logo.img
tz.img
xbl.img

3. Files I don't know if needed to flash, but at least a few for sure, iike bluetooth or dsp

aop.img
bluetooth.img
dsp.img
featenabler.img
imagefv.img
modem.img
oem_stanvbk.img
qupfw.img
reserve.img
storsec.img
system_ext.img
uefisecapp.img
xbl_config.img

But then there is the other problem with A/B parts of the firmware. Does anybody know more how we can make a working firmware updater? I already asked at XDA: https://forum.xda-developers.com/t/rom-official-lineageos-17-1-oneplus-nord-avicii.4185373/page-12#post-84714269 but until now nobody answered.

Best

Tim

**Comment by angela-d** [comment]
Oneplus seem to be coming out with new phones every month!!

I don't have any of the new models to test with, but for most .img files, you can mount and browse it's contents:
- [Windows](https://www.tenforums.com/tutorials/3579-mount-unmount-iso-img-file-windows-10-a.html)
- [Mac](https://apple.stackexchange.com/questions/65678/opening-mounting-a-img-file)
- [Linux](https://fossbytes.com/mounting-isos-image-file-types-in-linux/)

If you're able to find the modem and radio files, someone willing to test with their device could give it a go and see if this script could work on the newer models with a few modifications.

**Comment by angela-d** [comment]
I assume by now you guys have found solutions, but referencing this in case not.

[Payload dumper go](https://github.com/ssut/payload-dumper-go) might work if your firmwares are bundled in payloads.
